version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: educational_system_db
    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_DATABASE: ${DB_NAME:-educational_system}
      MYSQL_USER: ${DB_USER:-edu_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-edu_password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_/var/lib/mysql
    networks:
      - edu_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    
    container_name: educational_system_web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db

      
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    networks:
      - edu_network
  


volumes:
  db_


networks:
  edu_network:
    driver: bridge